add support postgres hive metastore
bitsondatadev/hive-metastore pull request #2
Opened 2022-06-18 22:28 UTC by evolv34

2022-06-18 22:29 UTC, evolv34 commented
add support postgres hive metastore

2022-08-30 15:11 UTC, bitsondatadev requested changes

2022-08-30 15:11 UTC, bitsondatadev commented on conf/core-site.xml
> +        <value>s3a://minio:9000</value>
I wouldn't include these files in this Docker image. I'd like to keep this image clean and requiring you to use as few specific settings as possible so that theoretically you could point it to an S3 bucket you have on your's or your company's cloud storage.

2022-08-30 15:11 UTC, bitsondatadev commented on docker-compose.yml
> +      METASTORE_DB_HOSTNAME: postgres
Same with this file. Let's keep these files in other projects that use this image

2022-08-30 15:12 UTC, bitsondatadev commented
Sorry for the late reply @evolv34, I started the review and never pushed submit. :/

2023-01-20 03:25 UTC, evolv34 commented
Hi @bitsondatadev any update on this PR ?!

2023-01-20 03:34 UTC, evolv34 commented
Hi @bitsondatadev I addressed PR comments. Could you please review it ?

2023-01-20 03:35 UTC, evolv34 commented on conf/core-site.xml
> +        <value>s3a://minio:9000</value>
Removed this file.

2023-01-20 03:35 UTC, evolv34 commented on docker-compose.yml
> +      METASTORE_DB_HOSTNAME: postgres
Removed this file.

2023-01-20 15:25 UTC, bitsondatadev approved these changes
LGTM, Thanks @evolv34!

2023-01-20 15:25 UTC, merged